/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as CapaRouteImport } from './routes/capa'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as DocumentsDocIdRouteImport } from './routes/documents.$docId'
import { Route as StagesStageIdRouteImport } from './routes/stages.$stageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const CapaRoute = CapaRouteImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocumentsRoute,
} as any)
const StagesStageIdRoute = StagesStageIdRouteImport.update({
  id: '/stages/$stageId',
  path: '/stages/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/guidance': typeof GuidanceRoute
  '/integrations': typeof IntegrationsRoute
  '/manual': typeof ManualRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/stages/$stageId': typeof StagesStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/guidance': typeof GuidanceRoute
  '/integrations': typeof IntegrationsRoute
  '/manual': typeof ManualRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/stages/$stageId': typeof StagesStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/capa': typeof CapaRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/guidance': typeof GuidanceRoute
  '/integrations': typeof IntegrationsRoute
  '/manual': typeof ManualRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/stages/$stageId': typeof StagesStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/capa'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/guidance'
    | '/integrations'
    | '/manual'
    | '/documents/$docId'
    | '/stages/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audits'
    | '/capa'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/guidance'
    | '/integrations'
    | '/manual'
    | '/documents/$docId'
    | '/stages/$stageId'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/capa'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/guidance'
    | '/integrations'
    | '/manual'
    | '/documents/$docId'
    | '/stages/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRoute
  CapaRoute: typeof CapaRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  GuidanceRoute: typeof GuidanceRoute
  IntegrationsRoute: typeof IntegrationsRoute
  ManualRoute: typeof ManualRoute
  StagesStageIdRoute: typeof StagesStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capa': {
      id: '/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof CapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/stages/$stageId': {
      id: '/stages/$stageId'
      path: '/stages/$stageId'
      fullPath: '/stages/$stageId'
      preLoaderRoute: typeof StagesStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocIdRoute: typeof DocumentsDocIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocIdRoute: DocumentsDocIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRoute,
  CapaRoute: CapaRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  GuidanceRoute: GuidanceRoute,
  IntegrationsRoute: IntegrationsRoute,
  ManualRoute: ManualRoute,
  StagesStageIdRoute: StagesStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
